name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: cmake make nasm gcc-multilib g++-multilib grub-pc-bin grub-efi-ia32-bin dosfstools mtools xorriso zstd unzip wget

      - name: Build towboot image
        run: HHUOS_REDISTRIBUTABLE_BUILD=1 ./build.sh --target towboot --type Debug && wget -O lvgl-licence.txt https://raw.githubusercontent.com/lvgl/lvgl/master/LICENCE.txt

      - name: Build limine image
        run: HHUOS_REDISTRIBUTABLE_BUILD=1 ./build.sh --target limine --type Debug && wget -O limine-licence.txt https://raw.githubusercontent.com/limine-bootloader/limine/trunk/COPYING

      - name: Build grub image
        run: HHUOS_REDISTRIBUTABLE_BUILD=1 ./build.sh --target grub --type Debug

      - name: Create artifact
        run: tar -czvf hhuOS.tar.gz hhuOS-limine.iso hhuOS-towboot.img hdd0.img floppy0.img run.sh efi/build.sh limine-licence.txt lvgl-licence.txt README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hhuOS
          path: hhuOS.tar.gz